# Generated by Django 4.2.1 on 2023-06-22 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0068_balance_sheet_payments1_profit_loss_payments1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='challan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chal_no', models.CharField(max_length=100)),
                ('challan_date', models.DateField()),
                ('challan_type', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('cx_mail', models.CharField(max_length=100)),
                ('billto', models.TextField(max_length=100)),
                ('taxamount', models.CharField(max_length=100)),
                ('igst', models.CharField(max_length=100)),
                ('cgst', models.CharField(max_length=100)),
                ('sgst', models.CharField(max_length=100)),
                ('subtotal', models.CharField(max_length=100)),
                ('grand', models.CharField(max_length=100)),
                ('pl', models.CharField(max_length=100)),
                ('note', models.TextField(max_length=100)),
                ('file', models.FileField(default='default.png', upload_to='challan/')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Invoiced', 'Invoiced')], default='Draft', max_length=150)),
                ('ref', models.TextField(max_length=100)),
                ('shipping', models.IntegerField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='challanitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.TextField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('hsn', models.TextField(max_length=255)),
                ('tax', models.FloatField()),
                ('total', models.FloatField()),
                ('desc', models.TextField(max_length=255)),
                ('rate', models.FloatField()),
                ('discount', models.IntegerField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
                ('dl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.challan')),
            ],
        ),
    ]
