# Generated by Django 4.2.1 on 2023-06-22 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0069_challan_mod_challanitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mod',
        ),
    ]
