# Generated by Django 4.2.1 on 2023-06-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0069_challan_challanitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='challan_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
