# Generated by Django 4.2.1 on 2023-06-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0069_challancreate'),
    ]

    operations = [
        migrations.CreateModel(
            name='dlchallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.TextField(max_length=100)),
                ('hsn', models.IntegerField()),
                ('dsc', models.TextField(max_length=100)),
                ('qty', models.IntegerField()),
                ('tax', models.TextField(max_length=100)),
                ('total', models.FloatField()),
            ],
        ),
    ]
