# Generated by Django 4.2.1 on 2023-06-16 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0070_challan_challan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='challanitem',
            name='cid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
            preserve_default=False,
        ),
    ]
