# Generated by Django 4.2.1 on 2023-06-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0070_delete_mod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='cgst',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='challan',
            name='grand',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='challan',
            name='igst',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='challan',
            name='sgst',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='challan',
            name='subtotal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='challan',
            name='taxamount',
            field=models.FloatField(),
        ),
    ]
