# Generated by Django 4.2.1 on 2023-06-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0071_alter_challan_cgst_alter_challan_grand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='cgst',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='challan',
            name='igst',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='challan',
            name='sgst',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='challan',
            name='taxamount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='challanitem',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='challanitem',
            name='tax',
            field=models.FloatField(default=0),
        ),
    ]
