# Generated by Django 4.2.1 on 2023-06-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0072_alter_challan_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Invoiced', 'Invoiced')], default='Draft', max_length=150),
        ),
    ]
