# Generated by Django 4.2.1 on 2023-06-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0072_alter_challan_cgst_alter_challan_igst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challanitem',
            name='tax',
            field=models.IntegerField(default=0),
        ),
    ]
