# Generated by Django 4.2.1 on 2023-06-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0073_alter_challan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='ref',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
