# Generated by Django 4.2.1 on 2023-08-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0074_banking_g_bank_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_transaction',
            name='cash_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
