# Generated by Django 4.2.1 on 2023-08-12 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0074_banking_g'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank_transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_trans', models.TextField(max_length=100)),
                ('to_trans', models.TextField(max_length=100)),
                ('amount', models.IntegerField()),
                ('adj_date', models.DateField()),
                ('desc', models.TextField(max_length=100)),
                ('type', models.TextField(max_length=100)),
                ('banking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.banking_g')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
    ]
