# Generated by Django 4.2.1 on 2023-08-17 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0074_banking_g_cash_hand_bank_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='cheques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chq_type', models.TextField(max_length=100)),
                ('chq_name', models.TextField(max_length=100)),
                ('chq_ref_no', models.TextField(max_length=100)),
                ('chq_date', models.DateField(blank=True, null=True)),
                ('chq_amount', models.IntegerField(blank=True, null=True)),
                ('chq_status', models.CharField(default='Active', max_length=100)),
                ('chq_action', models.TextField(max_length=100)),
                ('banking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.banking_g')),
                ('cash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.cash_hand')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
    ]
