# Generated by Django 4.2.1 on 2023-08-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0075_alter_bank_transaction_cash_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_transaction',
            name='adj_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bank_transaction',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bank_transaction',
            name='cash_cash',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
