# Generated by Django 4.2.1 on 2023-08-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0075_cheques'),
    ]

    operations = [
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_date', models.DateField(blank=True, null=True)),
                ('trans_partyname', models.TextField(max_length=100)),
                ('trans_type', models.TextField(max_length=100)),
                ('trans_total', models.IntegerField(blank=True, null=True)),
                ('trans_received', models.IntegerField(blank=True, null=True)),
                ('trans_balance', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
