# Generated by Django 4.2.1 on 2023-08-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0076_alter_banking_g_openingbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_transaction',
            name='balance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
