# Generated by Django 4.2.1 on 2023-08-26 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0077_retainerinvoiceitems_retainerinvoices_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='recinvoice',
            fields=[
                ('recinvoiceid', models.AutoField(primary_key=True, serialize=False, verbose_name='REC_INVOICEID')),
                ('customername', models.CharField(max_length=100)),
                ('profilename', models.CharField(max_length=100)),
                ('recinvoiceno', models.IntegerField(default=1000)),
                ('terms', models.CharField(default='', max_length=100)),
                ('startdate', models.CharField(default='', max_length=100)),
                ('enddate', models.CharField(default='', max_length=100)),
                ('bname', models.CharField(default='', max_length=255)),
                ('placosupply', models.CharField(default='', max_length=100)),
                ('ordernumber', models.IntegerField(default=0, null=True)),
                ('repeate_every', models.CharField(default=0, max_length=100)),
                ('amtrecvd', models.IntegerField(default=0, null=True)),
                ('taxamount', models.IntegerField(default=0, null=True)),
                ('baldue', models.FloatField()),
                ('subtotal', models.IntegerField(default=0, null=True)),
                ('grandtotal', models.FloatField(default=0, null=True)),
                ('recinvoice_orderno', models.CharField(default='', max_length=255, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Approved', 'Approved'), ('Billed', 'Billed')], default='Draft', max_length=150)),
                ('note', models.CharField(default='', max_length=255, null=True)),
                ('file', models.FileField(default='default.jpg', upload_to='invoice')),
                ('IGST', models.CharField(default=0, max_length=100, null=True)),
                ('CGST', models.CharField(default=0, max_length=100, null=True)),
                ('SGST', models.CharField(default=0, max_length=100, null=True)),
                ('TCS', models.CharField(default=0, max_length=100, null=True)),
                ('gsttype', models.CharField(max_length=100, null=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='recinvoice_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('discount', models.IntegerField(default=0, null=True)),
                ('description', models.CharField(default='', max_length=100)),
                ('qty', models.IntegerField(default=0, null=True)),
                ('price', models.CharField(max_length=100)),
                ('total', models.IntegerField(default=0, null=True)),
                ('tax', models.CharField(max_length=100)),
                ('hsn', models.CharField(max_length=100)),
                ('items', models.CharField(max_length=100, null=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
                ('recinvoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.recinvoice')),
            ],
        ),
    ]
