# Generated by Django 4.2.1 on 2023-08-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0077_bank_transaction_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank_transaction',
            name='balance',
        ),
        migrations.AddField(
            model_name='banking_g',
            name='balance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
